### ISSUE TITLE
Support Tornado 5.x

### ISSUE THREAD

**Issue by fantix** [fantix/gino#152]
Refs #151

**Comment by AmatanHead** [comment]
Hello! So, I've looked into tornado 5.1 and it seems we can drop major part of compatibility layer introduced in the current tornado extension. That is, `AsyncioRequestHandler` will finally go away.
So the question is, do we want to support `tornado<5.0`? I'd vote for no. Reason is, ORM is something fundamental, something that you choose at the very beginning of a project and stick to it forever. Changing ORM is pain. So, given that GION is a relatively young library, it's unlikely it'll be integrated into an existing project. And for new projects there is no problem in upgrading tornado.

**Comment by fantix** [comment]
Yeah I agree with you. If no objection, let's drop `Tornado<5.0` support in possibly GINO 0.7.

What do you think about supporting both Tornado 5.0 and 5.1 after 5.1 is released? Or keeping just 5.1 support for simplicity?

**Comment by AmatanHead** [comment]
> What do you think about supporting both Tornado 5.0 and 5.1 after 5.1 is released?

I don't think there will be something that needs us to break back-compatimiblity, so supporting both 5.0 and 5.1 sounds ok. After all, there well be no crunches or monkey-patching that we need to maintain.

I'm planning to start working on pull request later next week.

**Comment by fantix** [comment]
Great! Thank you!

**Comment by AmatanHead** [comment]
The tornado doesn't have any robust setup/teardown mechanism. That is, its `prepare()` is called after `check_xsrf_cookie()` and its `on_finish()` cannot be async and it is only called on successful request finish.

Current tornado extension [overrides][1] the request handler's `_execure` method (see [the original tornado code][2]) in order to setup and teardown lazy connections. In this override, however, we have to copy error handling code ([this][3] thing in particular) from tornado's `_execute` to our `_execute`. This presents a potential compatibility problem, i.e. we'll have to adjust our extension every time tornado developers change the `_execute` method.

So I'd really like to remove all hacky things from the extension. Removing this particular thing, however, means that we'll have to remove the entire `use_connection_for_request` mechanism.

@fantix what do you think about it?

[1]: https://github.com/fantix/gino/blob/357e2111d8ec824c08d99e4c6c6fe1042a3412ac/gino/ext/tornado.py#L381
[2]: https://github.com/tornadoweb/tornado/blob/35a538f50e704e348926e1b113bc03328a1da9f2/tornado/web.py#L1505
[3]: https://github.com/fantix/gino/blob/357e2111d8ec824c08d99e4c6c6fe1042a3412ac/gino/ext/tornado.py#L430

**Comment by fantix** [comment]
Guess we'll have to remove that if we cannot find a concrete hook to close a connection. There's already plenty of hacky copies for secondary features (`create_all` and `drop_all`), it would be the best not to keep more on site.
