### ISSUE TITLE
alias() causes RowProxy not model instances to be returned

### ISSUE THREAD

**Issue by aglassdarkly** [fantix/gino#222]
* GINO version: 0.7.0
* Python version: 3.6.3
* Operating System: ubuntu 17.04

### Description

Gino is answering a list of RowProxy instances instead of model instances for the query below.

### What I Did

```python
    q = Thing.query.alias().select()
    results = await q.gino.all()
```

generated sql:
```sql
SELECT anon_1.created, anon_1.updated, anon_1.id, anon_1.data 
FROM (SELECT thing.created AS created, thing.updated AS updated, thing.id AS id, thing.data AS data 
FROM thing) AS anon_1
```

results is a list of RowProxy instances, not instances of Thing.

**Comment by fantix** [comment]
Background: `Model.query` adds an execution option `model` to the returning query, causing the returning result to be instances of the `model` type.

Looks like `sqlalchemy.sql.selectable.Alias` does copied the execution options, it shouldn't be blamed. Looking into the SQLAlchemy code, `select()` is the key:

        def select(self, whereclause=None, **params):
            return Select([self], whereclause, **params)

where `self` is an `Alias` instance with the execution options. In this case, `Select` didn't copy it over, because there might be several selectables to select from. Likely, it will return `RowProxy` instead of model instances even without `alias()`.

For me this is not an issue, because `selectable.select()` is just a short for `db.select([selectable])` which generates a new SQLAlchemy query, and we are only by default returning model instances on queries directly generated by the model. For example, `db.select([Thing])` would also return `RowProxy`.

If it is needed to return model instances, you can manually set the `model` execution option like this:

    q = Thing.query.alias().select()
    results = await q.gino.model(Thing).all()

Or use the model loader which is the same under the hood:

    q = Thing.query.alias().select()
    results = await q.gino.load(Thing).all()

Or you may want it on the query for further tweaks:

    q = Thing.query.alias().select().execution_options(loader=Thing)

**Comment by aglassdarkly** [comment]
Thank you for the very detailed response! This clears up some confusion on my part. The last option works great for what we're doing.

**Comment by fantix** [comment]
Cool, glad to know it works for you!

**Comment by fantix** [comment]
I'm closing this issue, please feel free to reopen for further discussion.
