### ISSUE TITLE
transaction context manager not rolling back on exception

### ISSUE THREAD

**Issue by aglassdarkly** [fantix/gino#228]
* GINO version: 0.7.3
* Python version: 3.6.3
* Operating System: Ubuntu 17.10

### Description

Transaction context manager doesn't roll back on exception.

### What I Did
```python
        async with db.transaction():
            await instance.update(name='splunge').apply()
            raise RuntimeError
```
Upon exiting the context manager, the instance row has been modified to the new value.

**Comment by fantix** [comment]
Ah, my bad for not having `crud.rst` docs done yet.

I believe the transaction did roll back in database, it is only that the `instance.name` remained `splunge` after exiting the context manager by an exception? That is just the current situation I should have documented about. I'll explain in detail below.

First, current design treats model instances as pure-memory stateless data objects. That is to say, once its value is changed, there's no way for GINO to revert the change, because GINO won't keep a copy, even if the change is made through GINO API.

That is exactly what is happening here - `Model.update()` is pure memory change, `instance.name` was already `splunge` even before `apply()` was invoked, and it will remain `splunge` no matter whether `apply()` succeeds nor not, or how this transaction ends.

It is designed this way because we don't want to implicitly mess up with in-memory instance values with rollbacks, even though in this case it is a bit odd. That's why I split `apply()` from `update()`, so that you know that you are firstly changing the instance in memory, then tries to apply the same change into database. The transaction fails, database is rolled back, but not the memory value of the instance. It is truly a surprise - even for me after a while - but I think it is a tradeoff to keep the design simple.

Please feel free to post a different idea - the current inconsistent result is a bit frustrating for me too.

**Comment by aglassdarkly** [comment]
Thanks for the detailed reply. I agree that the instance should be separate from the database and shouldn't revert. In my case, however, the database value is committed and not rolled back. Here is a complete example.

```python
import asyncio

from gino import Gino

db = Gino()


class Test(db.Model):
    __tablename__ = 'test'

    id = db.Column(db.String, primary_key=True)


async def test():
    await db.set_bind('postgresql://test:test@localhost:5432/test')
    inst = await Test.create(id='before')
    async with db.transaction():
        await inst.update(id='after').apply()
        raise RuntimeError


if __name__ == '__main__':
    asyncio.ensure_future(test())
    asyncio.get_event_loop().run_until_complete(test())
```

Starting with an empty table, after execution the table has one row with the id of 'after'.

**Comment by fantix** [comment]
Ah! That’s weird, looks like a bug. I’ll check this tomorrow morning when I have my computer.

**Comment by fantix** [comment]
Eventually figured out - you should `pip install aiocontextvars` to have the context work correctly, or you'll have to explicitly specify the connection for the update like this:

```python
    async with db.transaction() as tx:
        await inst.update(id='after').apply(bind=tx.connection)
        raise RuntimeError
```

**Comment by fantix** [comment]
Yes you’re right. Let me try to add a warning for it.

**Comment by wwwjfy** [comment]
I'm thinking instead of warnings, shall we raise `ImportError` without implementing the fake `ContextVar`? I assume that won't fit in most of scenarios and warnings can be easily overlooked.

**Comment by fantix** [comment]
Makes sense! `ImportError` it shall be.
