### ISSUE TITLE
Cascade delete?

### ISSUE THREAD

**Issue by Ovyerus** [fantix/gino#476]
### Description
Suppose you have a set of models like the following
```py
db = Gino()

class User(db.Model):
    __tablename__ = "user"

    id = db.Column(db.Numeric(), primary_key=True)
    username = db.Column(db.Unicode())


class Mod(db.Model):
    __tablename__ = "mod"

    id = db.Column(db.Numeric(), primary_key=True)
    title = db.Column(db.Unicode())

class UserMod(db.Model):
    __tablename__ = "user_mod"

    user_id = db.Column(None, db.ForeignKey("user.id"))
    mod_id = db.Column(None, db.ForeignKey("mod.id"))
```

Trying to delete a user that has a relation in `UserMod` like
```py
await User.delete.where(User.id == user_id).gino.status()
# or 
user = await User.get(user_id)
await user.delete()
```
results in an error message similar to this
![error](https://erisa.is-a-good-waifu.com/2kmguTk.png)

Is there anyway to do a cascade delete (deleting other rows linked via keys)?

**Comment by fantix** [comment]
Thanks for the question! GINO won't do cascade delete for you. So if you need to delete referenced rows, you need to either explicitly do that, or use the `CASCADE` action on `ON DELETE` clause for the [foreign key constraints](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS).

Please note, as you are defining a many-to-many relationship in your example, the `ON DELETE CASCADE` foreign key will only clean up the broken relationship for you. For example, if you delete a user, no mod will be deleted, only rows in `user_mod` will be deleted by the cascade.

In order to delete any orphaned mods too when deleting users, database triggers on `user_mod` might be one solution.

**Comment by Ovyerus** [comment]
Fair enough, and yeah I figured that about the many-to-many. Would it possible to add something like `model.delete(cascade=True)` for easily doing cascade delete?
