### ISSUE TITLE
Problem with db.transaction

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#57]
* GINO version: 0.5.0
* Python version: 3.6.2
* Operating System: ubuntu 14.04

### Description

Create , update, delete actions should all rollback, but only update and delete action rollback.

### What I Did

```
@bp.get('/d0418')
async def use_postgres18(request):
    db = request.app.db
    await User.delete.gino.all()
    await User.create(nickname='testonly')

    async with db.transaction() as (conn, tx):
        try:
            await User.create(nickname='testonly2')
            await User.update(nickname='fantix').apply()
            await User.delete.gino.all()
            raise Exception
        except:
            pass

    users = await User.query.gino.all()
    return ajax_data({'users':users})
```
` User.create(nickname='testonly2')` action not rollback.

**Comment by jonahfang** [comment]
Sorry, following code works:
```
    try:
        async with db.transaction() as (conn, tx):
            u = await User.create(nickname='testonly2')
            await u.update(nickname='fantix').apply()
            await User.delete.gino.all()
            raise Exception
    except:
        pass

```

**Comment by jonahfang** [comment]
I have writen an decorator for Sanic view:
```
def require_transaction():
    def decorator(f):
        @wraps(f)
        async def decorated_function(request, *args, **kwargs):
            db = request.app.db
            try:
                async with db.transaction() as (conn, tx):
                    return await f(request, *args, **kwargs)
            except:
                log_exc()
                return json({'status': 'exception'}, 400)

        return decorated_function
    return decorator

```

**Comment by wwwjfy** [comment]
To be concise, there is nothing wrong to have `try..except` in the transaction context.

No rollback happens in the first example because the exception is caught and handled _inside_ the context, so the transaction knows nothing about the exception. In the bigger picture, the exception is expected, so it shouldn't cause rollback.

There are generally two reasons for rollback. 1) A _SQL_ error occurs, e.g. duplicate primary key, then the transaction is not commit-able. That's how Postgresql works. 2) Unhandled exception raised.
