### ISSUE TITLE
GINO's transaction() method always return None as a second tuple element

### ISSUE THREAD

**Issue by AmatanHead** [fantix/gino#59]
Hello!

Right now, `GinoTransaction.__aenter__` returns the result of the underlying transaction wrapper's `__aenter__`:

```python
# self._ctx is usually an asyncpg.Transaction instance
return conn, await self._ctx.__aenter__()
```

However, `asyncpg.Transaction.__aenter__()` [doesn't return anything](https://github.com/MagicStack/asyncpg/blob/master/tests/test_transaction.py#L24).

I propose either returning `(conn , self._ctx)` from the `GinoTransaction.__aenter__` or changing signature of the `.transaction()` method to return just a connection (or maybe nothing).

**Comment by fantix** [comment]
Ah that's a surprise to me!

I vote for returning just a connection. Because:

1. With a managed `asyncpg.Transaction` object, user can do nothing with it.
2. The connection object is still required, because without enabling the task local context, it would be not possible to make use of `db.transaction` at all.

One other idea is that, should GINO support using `db.transaction` without `async with`, like asyncpg does. So that one could do such:

```python
tx = db.transaction()
conn = await tx.start()
try:
    ...
except:
    await tx.rollback()
    raise
finally:
    await tx.commit()
```

**Comment by AmatanHead** [comment]
Returning a `connection` object from something that's called `transaction` seems odd to me. I have no better alternative though.

I'l try deriving `GinoTransaction` from asyncpg's `Transaction` and send a pullrequest.

**Comment by fantix** [comment]
And it should be really a part of `pool.py` instead of `api.py`. Yeah it is a bit weird, I suppose there's not much left to choose if we still want to keep this shortcut. Thanks for the effort!

**Comment by AmatanHead** [comment]
I've just realized this is not going to work.

First, implementing a separate `GinoTransaction` with `start`, `stop` etc. may confuse users: while `db.transaction()` returns an instance of `GinoTransaction`, `conn.transaction()` returns a plain asyncpg's `Transaction`.

Second, in readme you write:

> Please note, there is no db.release to return the connection to the pool, thus you cannot do `conn = await db.acquire()`. Using async with is the only way, and the reason is about context...

The same thing applies to transactions. While you can't break your local state by fiddling with transaction, it's still a bit unnatural to have the ability to stop a transaction and, in the same time, to lack the ability to return a connection to its pool. Even more, you can actually return a connection by simply calling `conn.release()` or so (I use it in the tornado extension).

Therefore, a deeper problem arise. We should unify these interfaces. We also should take into account the implicit nature of the task local (e.g. it's too simple to forget when they work and when they don't) state and make it more explicit.

Right now, I have no clear conception on how to fix this. I'll think about it.

**Comment by fantix** [comment]
> Second, in readme you write:
> 
> > Please note, there is no db.release to return the connection to the pool, thus you cannot do `conn = await db.acquire()`. Using async with is the only way, and the reason is about context...
> 

Ah this is an outdated statement after 0.5.0, which followed the asyncpg pattern for `db.transaction` implementation. I'll update it.

> The same thing applies to transactions. While you can't break your local state by fiddling with transaction, it's still a bit unnatural to have the ability to stop a transaction and, in the same time, to lack the ability to return a connection to its pool. Even more, you can actually return a connection by simply calling `conn.release()` or so (I use it in the tornado extension).
> 
> Therefore, a deeper problem arise. We should unify these interfaces. We also should take into account the implicit nature of the task local (e.g. it's too simple to forget when they work and when they don't) state and make it more explicit.

You are right about it. I wonder what if I started a transaction in asyncpg, and return the connection to pool before transaction is closed in vanilla asyncpg ~~

> Right now, I have no clear conception on how to fix this. I'll think about it.

Thanks! I'm trying too.

**Comment by fantix** [comment]
Just got another idea here. How about hiding the asyncpg interfaces at all, and expose an unique GINO db access API? So that:

1. There will be no more confusion
2. May even be able to adapt other database drivers other than asyncpg

**Comment by fantix** [comment]
I'm trying to implement an `engine`-like class, similar to SQLAlchemy but continued more with what GINO offered. `Pool` of asyncpg will be a composition, instead of a parent class. And possibly hiding the connection concept. I'll push the code to a branch, your advices are welcome.

**Comment by AmatanHead** [comment]
> I'm trying to implement an engine-like class

Are you still on this? What's the current status on the library? Haven't seen any progress for a while.

**Comment by fantix** [comment]
Oh yes I was working in branch t59 for this one, just busy working for food recently. I’m trying to complete work at hand and get this done in Feb during Chinese new year =)

**Comment by fantix** [comment]
Some update:
The work from last October was completely off the road. I felt like there was too much similarity between the new `Engine`-like interface, and vanilla SQLAlchemy interface. So instead of composition, I **inherited** SQLAlchemy `Engine`, then the `Connection`, then quickly everything. Now in the branch, there is a looks-compatible SQLAlchemy dialect for asyncpg, and a SQLAlchemy strategy for asyncio, with which one could already write pure async SQLAlchemy code.

But the drawback is severe. First, it is hacky. Without modifying SQLAlchemy code, there're a lot of tricks around underlying SQLAlchemy code and ugly hacks which are easily broken. Second, it is not complete and misleading. It may eventually take a long time to asynchronize 100% SQLAlchemy code. Before that is done - no doubt in a hacky way - some feature seems to work but actually not. For example, the SQLAlchemy hooks are triggered in completely different order, and executed in non-aysnc context. The same for some error handlers. Not to mention much more else.

I gave a try these two days [forking SQLAlchemy and tried to asynchronize it from upstream](https://github.com/decentfox/sqlalchemy), using some of the same work done in GINO. A simple query is working, but the result seems to be a dead end - almost every piece of core SQLAlchemy code needs to be asynchronized, in a way that the same code could run in both sync and async mode. Also I was trying to keep the formal SQLAlchemy structure, so that it brings least impact to its stability. But still, the solution doubles the number of methods need to be asynchronized, and it won't be an acceptable solution for both parties.

So I think perhaps it is time to get back to the beginning, to simply make an `Engine`-like composition. SQLAlchemy keeps its role as a SQL translator, and GINO takes care of all the other asynchronous magic.

**Comment by fantix** [comment]
New transaction interface merged into master, closing this now.
