### ISSUE TITLE
Publish another minor version

### ISSUE THREAD

**Issue by RmStorm** [fantix/gino#596]
Is it possible to publish another minor version on pypi? Maybe configure automatic updating on pypi when a new version is tagged in the repo? Something like [this](https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags).

**Comment by fantix** [comment]
btw we have [this](https://github.com/fantix/gino/blob/37c85659a5fa8759ed3d3602bd8aa18b035b3bdd/.travis.yml#L4-L25), thanks for the suggestion!

**Comment by RmStorm** [comment]
ha, I completely missed it. Is it possible to push a new tag?

**Comment by fantix** [comment]
@wwwjfy what'd you think? Sry I didn't follow the recent PRs

**Comment by wwwjfy** [comment]
I think @RmStorm is looking for #592 to be published 😅
If it bothers you @RmStorm, I'm ok to create a new version, though I won't proactively publish just for it. :)

**Comment by RmStorm** [comment]
Yes, it's just a small bugfix but currently I have to manually work around it which is a hassle. I think it's just good practice to merge those little things right? It doesn't matter if the patch version increases to 20-30? I think the three PR's from py-up bot and dependabot (#548, #584, #594) should also be merged and published.

Isn't it just good CI practice to publish improvements? What's the point of having automated dependency updates and testing if they are not being merged and published? For 0.8.4 there were 8 bugfixes and features waiting to be merged, I think that is quite a lot! I think it would be appreciated if you guys (@fantix, @wwwjfy ) would consider merging more often and for smaller fixes. I would at least appreciate it  :smiley:

**Comment by wwwjfy** [comment]
Thanks for your suggestion. Personally, I'm not a fan of frequent updates, which only confuses users. (I know I don't like the trends started by Chrome with big version numbers, making it doesn't mean anything) I'm lazy on merging dependency updates because I don't want to have commit history filled with these.
For every release, I'd expect something more exciting, so that users won't just ignore and update, but can take some time reading the change logs.

Automated dependency updates, from my point of view, are to test if the updates may break backward compatibility so we're more aware and can take actions if needed.

**Comment by wwwjfy** [comment]
published v0.8.5
